import { TaskItem } from '../types';
import { getTaskDeadlineStatus } from './dateUtils';

export const TARGET_EMAIL = 'samsontsegayef@gmail.com';
export const TARGET_WHATSAPP = 'samsontsegaye26';

export interface DailyReminderPayload {
  email: string;
  whatsapp: string;
  subject: string;
  emailBody: string;
  whatsappMessage: string;
  tasksIncluded: number;
  delayedCount: number;
  inProgressCount: number;
}

/**
 * Formats a rich daily reminder email body for all tasks or specific target tasks.
 */
export function buildDailyTaskEmailContent(
  tasks: TaskItem[],
  asOfDate: string,
  targetTask?: TaskItem
): { subject: string; body: string } {
  if (targetTask) {
    const deadlineInfo = getTaskDeadlineStatus(targetTask.endDate, targetTask.status, asOfDate);
    const delay = deadlineInfo.category === 'OVERDUE' ? Math.abs(deadlineInfo.daysDiff || 0) : (targetTask.delayDays || 0);

    const subject = `[CBE Daily Task Reminder] Task #${targetTask.sNo}: ${targetTask.deliverable || targetTask.title} (${targetTask.status})`;
    const body = `Dear Samson,

Here is your daily task milestone reminder for the Wholesale Banking Customer Onboarding & Loan Origination System (Action Plan):

===================================================================
TASK DETAILS (As of ${asOfDate})
===================================================================
• Deliverable #${targetTask.sNo}: ${targetTask.deliverable || targetTask.title}
• Workstream: ${targetTask.workstream}
• Current Status: ${targetTask.status}
• Scheduled Timeline: ${targetTask.startDate} to ${targetTask.endDate}
• Backend Lead: ${targetTask.backendOwner || '-'}
• Frontend Lead: ${targetTask.frontendOwner || '-'}
• Progress: ${targetTask.percentComplete ?? 0}%
• Delay Horizon: ${delay > 0 ? `+${delay} Days Overdue` : '0 Days (On-Track)'}
• Prerequisites / Dependency: ${targetTask.dependency || 'None'}
• Remarks / Blockers: ${targetTask.delayReason || targetTask.remark || 'On track with sprint milestones'}

===================================================================
RECOMMENDED PMO ACTION
===================================================================
1. Check daily engineering standup sync with ${targetTask.backendOwner} and ${targetTask.frontendOwner}.
2. Confirm dependency handoffs are verified in staging.
3. Review SteerCo executive status log for target completion.

Recipient: ${TARGET_EMAIL}
WhatsApp Contact: ${TARGET_WHATSAPP}
Generated by Commercial Bank of Ethiopia (CBE) Digital Factory PMO Tracker.
`;
    return { subject, body };
  }

  // Master Daily Summary Email
  const total = tasks.length;
  const inProgressTasks = tasks.filter(t => t.status === 'In Progress' || t.status === 'Partial');
  const delayedTasks = tasks.filter(t => {
    const info = getTaskDeadlineStatus(t.endDate, t.status, asOfDate);
    return info.category === 'OVERDUE' || t.status === 'Delayed' || (t.delayDays && t.delayDays > 0);
  });
  const completedCount = tasks.filter(t => t.status === 'Completed').length;

  const subject = `[CBE Daily Action Plan Reminder] Daily Operational Status - ${asOfDate} (${inProgressTasks.length} Active, ${delayedTasks.length} Delayed)`;

  let taskLines = '';
  tasks.slice(0, 44).forEach(t => {
    const dl = getTaskDeadlineStatus(t.endDate, t.status, asOfDate);
    const delayDays = dl.category === 'OVERDUE' ? Math.abs(dl.daysDiff || 0) : (t.delayDays || 0);
    const delayFlag = delayDays > 0 ? ` [⚠️ +${delayDays}d DELAY]` : '';
    taskLines += `• #${t.sNo} [${t.status.toUpperCase()}] ${t.deliverable || t.title}\n   - Leads: ${t.backendOwner} (BE) / ${t.frontendOwner} (FE) | Due: ${t.endDate}${delayFlag}\n   - Dependency: ${t.dependency || 'None'}\n\n`;
  });

  const body = `Dear Samson Tsegaye,

This is your automated daily project tracking reminder for the "Wholesale Banking Customer Onboarding & Loan Origination System - Action Plan".

===================================================================
EXECUTIVE PORTFOLIO SNAPSHOT (As of ${asOfDate})
===================================================================
• Total Master Deliverables: ${total}
• Completed & Verified: ${completedCount} (${Math.round((completedCount / (total || 1)) * 100)}%)
• Active In Progress: ${inProgressTasks.length}
• Delayed / Critical Attention: ${delayedTasks.length}
• Target Delivery Lead: Samson Tsegaye (Technology Sector / PMO)

===================================================================
CRITICAL & AT-RISK DELIVERABLES
===================================================================
${delayedTasks.length > 0 ? delayedTasks.map(t => `▶ #${t.sNo} ${t.deliverable || t.title}\n   Owner: ${t.backendOwner} / ${t.frontendOwner} | Target: ${t.endDate} | Root Cause: ${t.delayReason || t.remark || 'Pending API alignment'}`).join('\n\n') : '✅ All currently active workstreams are running within baseline velocity.'}

===================================================================
DAILY TASK CATALOG (ALL 44 ACTION ITEMS)
===================================================================
${taskLines}
===================================================================
DISPATCH METADATA
===================================================================
Primary Email: ${TARGET_EMAIL}
WhatsApp Contact: ${TARGET_WHATSAPP}
Sent automatically via CBE Digital Factory Project Action Tracker.
`;

  return { subject, body };
}

/**
 * Builds clean WhatsApp text message for instant messaging.
 */
export function buildDailyTaskWhatsAppContent(
  tasks: TaskItem[],
  asOfDate: string,
  targetTask?: TaskItem
): string {
  if (targetTask) {
    const dl = getTaskDeadlineStatus(targetTask.endDate, targetTask.status, asOfDate);
    const delay = dl.category === 'OVERDUE' ? Math.abs(dl.daysDiff || 0) : (targetTask.delayDays || 0);

    return `📌 *CBE Daily Task Reminder (${asOfDate})*
━━━━━━━━━━━━━━━━━━━━
*Task #${targetTask.sNo}:* ${targetTask.deliverable || targetTask.title}
*Status:* ${targetTask.status} ${delay > 0 ? `(⚠️ +${delay}d Overdue)` : '✅'}
*Workstream:* ${targetTask.workstream}
*Target Date:* ${targetTask.endDate}
*Backend Lead:* ${targetTask.backendOwner || '-'}
*Frontend Lead:* ${targetTask.frontendOwner || '-'}
*Dependency:* ${targetTask.dependency || 'None'}
${targetTask.remark ? `*Remark:* ${targetTask.remark}` : ''}
━━━━━━━━━━━━━━━━━━━━
_Dispatched to Samson (${TARGET_WHATSAPP} / ${TARGET_EMAIL})_`;
  }

  const delayed = tasks.filter(t => {
    const info = getTaskDeadlineStatus(t.endDate, t.status, asOfDate);
    return info.category === 'OVERDUE' || t.status === 'Delayed';
  });
  const inProgress = tasks.filter(t => t.status === 'In Progress' || t.status === 'Partial');
  const completed = tasks.filter(t => t.status === 'Completed').length;

  return `📊 *CBE Daily Action Plan Reminder (${asOfDate})*
━━━━━━━━━━━━━━━━━━━━
*Project:* Wholesale Banking & Credit Digitization (MVP3)
*Total Deliverables:* 44
*Completed:* ${completed} | *Active:* ${inProgress.length} | *Delayed:* ${delayed.length}

*Critical Attention Items:*
${delayed.slice(0, 4).map(t => `• #${t.sNo} ${t.deliverable || t.title} (${t.backendOwner}/${t.frontendOwner}) - Due: ${t.endDate}`).join('\n')}

_Daily reminder sent to Samson (${TARGET_WHATSAPP} / ${TARGET_EMAIL})_`;
}

/**
 * Opens email client via mailto or Gmail direct web compose.
 */
export function openDirectEmailComposer(
  recipient: string = TARGET_EMAIL,
  subject: string,
  body: string
) {
  // Construct Gmail web composer URL for reliable browser dispatch
  const gmailUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(recipient)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  
  // Try opening Gmail composer in new window/tab, fallback to mailto
  const win = window.open(gmailUrl, '_blank');
  if (!win || win.closed || typeof win.closed === 'undefined') {
    // Popup blocked, use standard mailto:
    const mailtoUrl = `mailto:${encodeURIComponent(recipient)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = mailtoUrl;
  }
}

/**
 * Opens WhatsApp web / app with prefilled text message for samsontsegaye26.
 */
export function openWhatsAppComposer(
  recipientHandleOrPhone: string = TARGET_WHATSAPP,
  messageText: string
) {
  // If numeric phone digits provided (e.g. 251911...), use wa.me/phone, otherwise use wa.me/?text=
  const cleanPhone = recipientHandleOrPhone.replace(/[^0-9]/g, '');
  const url = cleanPhone.length >= 9
    ? `https://wa.me/${cleanPhone}?text=${encodeURIComponent(messageText)}`
    : `https://api.whatsapp.com/send?text=${encodeURIComponent(messageText)}`;
  
  window.open(url, '_blank');
}
